# Numpy

# Noufal Salim 

## This is Markdown test cell

## The material here was browsed along the internet if this violate any proprietary rights I am sorry in advance and please let me know

In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,5,8,6],float)

In [3]:
type(a)

numpy.ndarray

In [4]:
a

array([ 1.,  2.,  3.,  5.,  8.,  6.])

In [5]:
a[:3] #slicing operation

array([ 1.,  2.,  3.])

In [6]:
a[5]

6.0

In [7]:
a[1] = 4

In [8]:
a

array([ 1.,  4.,  3.,  5.,  8.,  6.])

In [9]:
a[1]== 5

False

## Matrix

In [10]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]],float)

In [11]:
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [12]:
b[0,1]

2.0

In [13]:
b[1,1] #Notice representation stats at node 0

5.0

In [14]:
b[0,:]

array([ 1.,  2.,  3.])

In [15]:
b[:,1]

array([ 2.,  5.,  8.])

In [16]:
b[-0:,-2:]

array([[ 2.,  3.],
       [ 5.,  6.],
       [ 8.,  9.]])

In [17]:
b.shape

(3, 3)

In [18]:
b.dtype #float64 is a numeric array that Numpy uses to store double-precision real numbers

dtype('float64')

In [19]:
len(b)

3

In [20]:
4 in b #chack if the value is present

True

In [21]:
b = b.reshape((1,9))

In [22]:
b

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [23]:
b=b.reshape((3,3))

In [24]:
b #total number of elements has to stay the same

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [25]:
c=b.reshape((1,9))

In [26]:
c

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [27]:
c=np.array(range(10),float)

In [28]:
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [29]:
d= c.copy

In [30]:
print c
print d

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
<built-in method copy of numpy.ndarray object at 0x7fa6489893f0>


In [31]:
d= c.tolist()

In [32]:
d

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [33]:
list(d)

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [34]:
e = c.tostring() #create binary string (didn't understand a bit;))

In [35]:
e

'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00"@'

In [36]:
e= np.fromstring(e)

In [37]:
e

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [38]:
c.fill(0)

In [39]:
c

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [40]:
b.transpose()

array([[ 1.,  4.,  7.],
       [ 2.,  5.,  8.],
       [ 3.,  6.,  9.]])

In [41]:
b # b remains the same

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [42]:
b == b.transpose() # checks element wise to output True of False(although I expected a single True or false statement)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]], dtype=bool)

In [43]:
c.flatten() # this changes the matrix into a list ;)kindof array actually

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [44]:
e = np.array(range(6),float)
f = np.array(range(3),float)
np.concatenate((e,f))

array([ 0.,  1.,  2.,  3.,  4.,  5.,  0.,  1.,  2.])

In [45]:
print a
a = a.reshape((3,2))
a

[ 1.  4.  3.  5.  8.  6.]


array([[ 1.,  4.],
       [ 3.,  5.],
       [ 8.,  6.]])

In [46]:
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [47]:
np.concatenate((a,b) , axis=1) #axis=1 stands for coloumn; since the dimension is different we cant do raw concatenation

array([[ 1.,  4.,  1.,  2.,  3.],
       [ 3.,  5.,  4.,  5.,  6.],
       [ 8.,  6.,  7.,  8.,  9.]])

In [48]:
a[:,np.newaxis]

array([[[ 1.,  4.]],

       [[ 3.,  5.]],

       [[ 8.,  6.]]])

In [49]:
a[np.newaxis,:]

array([[[ 1.,  4.],
        [ 3.,  5.],
        [ 8.,  6.]]])

In [50]:
np.arange(1,10,2, dtype=float) # 1 to 10 with difference 2

array([ 1.,  3.,  5.,  7.,  9.])

In [51]:
np.arange(0,10,2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8.])

In [52]:
np.ones((2,5), dtype=float) #create matrix of ones

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [53]:
np.zeros((5,2), dtype = float) #create matrix of zero

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [54]:
# 'zeros_like()' and 'ones_like()' create a matrix with same dimension with zero or one
np.zeros_like(a)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [55]:
np.ones_like(a)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [56]:
np.identity(3,dtype = float) # create identity matrix of given dimension

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [57]:
np.eye(4, k=1, dtype= float) #ones along the kth diogonal k=0 for identity matrix

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

## arthametical and mathematical operations on next notebook

python version 2.7 and numpy is used with anaconda in this notebook.
Basic matrix knowledge and basic programing knowledge is required to do this assignments