# Numpy

# Noufal Salim

## The material here was browsed along the internet if this violate any proprietary rights I am sorry in advance and please let me know

## understanding this module requires basic knowledge of matrix exponential and trignometrics, and a little programming.
## Thanks for viewing my GitHub

In [1]:
import numpy as np

Numpy array mathematics

In [2]:
a = np.array([1,2,3], float)

In [3]:
b = np.array([2,5,6], float)

In [4]:
a+b

array([ 3.,  7.,  9.])

In [5]:
a-b

array([-1., -3., -3.])

In [6]:
b-a

array([ 1.,  3.,  3.])

In [7]:
a*b #notice the multiplication is element wise for even matrix

array([  2.,  10.,  18.])

In [8]:
a/b

array([ 0.5,  0.4,  0.5])

In [9]:
b/a #since the array is declared float both division is possible

array([ 2. ,  2.5,  2. ])

In [10]:
b%a #modulus value

array([ 0.,  1.,  0.])

In [11]:
a**b #power corresponding elements eg: 2 to the power 5 for second element 

array([   1.,   32.,  729.])

In [12]:
#python automatically repeats the array to do mathematical operations

c = np.zeros((2,2),dtype = float)

In [13]:
d = np.array([2,1],float)

In [14]:
c+d

array([[ 2.,  1.],
       [ 2.,  1.]])

In [15]:
#we can use newaxis to specify how to braodcast
c+d[np.newaxis,:]

array([[ 2.,  1.],
       [ 2.,  1.]])

In [16]:
c+d[:,np.newaxis]

array([[ 2.,  2.],
       [ 1.,  1.]])

In [17]:
np.abs(c-d) #gives the absolute value

array([[ 2.,  1.],
       [ 2.,  1.]])

In [18]:
np.sign(c-d) #returns the sign of element with multiplier 1

array([[-1., -1.],
       [-1., -1.]])

In [19]:
np.sqrt(c+d)

array([[ 1.41421356,  1.        ],
       [ 1.41421356,  1.        ]])

In [20]:
np.log(c+d) #also have log10 

array([[ 0.69314718,  0.        ],
       [ 0.69314718,  0.        ]])

In [21]:
np.exp(d)

array([ 7.3890561 ,  2.71828183])

In [22]:
np.sin(d)

array([ 0.90929743,  0.84147098])

In [23]:
np.cos(d)

array([-0.41614684,  0.54030231])

In [24]:
np.tan(d)

array([-2.18503986,  1.55740772])

In [25]:
np.floor(np.tan(d)) #combining two functions 
#there is also ceil and rint(rounded) function

array([-3.,  1.])

In [26]:
np.rint(np.tan(d))

array([-2.,  2.])

In [27]:
np.ceil(np.pi) #np.pi returns pi value and np.e return e value

4.0

In [28]:
# we can loop numpy array using famous for loop
for element in np.tan(d):
    print element
#for multi axis array returns subsection of array(raw for example)

-2.18503986326
1.55740772465


In [29]:
print c+d
for (x,y) in c+d:
    print x*y

[[ 2.  1.]
 [ 2.  1.]]
2.0
2.0


## basic array operations

In [30]:
a = np.array(range(-10,10),float)
a = a.reshape(4,5)

In [31]:
a

array([[-10.,  -9.,  -8.,  -7.,  -6.],
       [ -5.,  -4.,  -3.,  -2.,  -1.],
       [  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.]])

In [32]:
np.sum(a)

-10.0

In [33]:
np.prod(a)

0.0

In [34]:
a.mean()

-0.5

In [35]:
np.mean(a) #both options are available

-0.5

In [36]:
a.var()

33.25

In [37]:
a.std()

5.7662812973353983

In [38]:
a.min()

-10.0

In [39]:
a.max()

9.0

In [40]:
a.argmin() #indices of min value in this case -10

0

In [41]:
a.argmax() #indices of max value in this case 9

19

In [42]:
#argument axis in the above given functions specify the row or coloumn to operation
a.mean(axis = 0) #axis zero gives the row

array([-2.5, -1.5, -0.5,  0.5,  1.5])

In [43]:
a.mean(axis=1) #axis one gives the coloumn

array([-8., -3.,  2.,  7.])

In [44]:
#we can use the sort() function to sort the elements completely or axis wise since the elements are sorted over row
#in this case let me try coloumn sorting 
a.sort(axis = 1)
a
#still the answer is same SORRY

array([[-10.,  -9.,  -8.,  -7.,  -6.],
       [ -5.,  -4.,  -3.,  -2.,  -1.],
       [  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.]])

In [45]:
a.clip(-9,5) #caps the elements to a specific range

array([[-9., -9., -8., -7., -6.],
       [-5., -4., -3., -2., -1.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  5.,  5.,  5.,  5.]])

In [46]:
np.unique(a.clip(-9,5))

array([-9., -8., -7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,
        4.,  5.])

In [47]:
a.diagonal()

array([-10.,  -4.,   2.,   8.])

## comparison

In [48]:
a < a.clip(-9,5)

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [49]:
a > a.clip(-9,5)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]], dtype=bool)

In [50]:
a == a.clip(-9,5)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False]], dtype=bool)

In [51]:
a >= a.clip(-9,5)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [52]:
a > 0 #broadcasting is used here

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [53]:
#any() and all() can be used to check any or all of the boolean elements are true or not
#any can also used to check whether the array have any elements

## logical operations

In [54]:
b = np.logical_and(a>=0,a<=9)
b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [55]:
c = np.logical_not(b)
c

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [56]:
d = np.logical_or(b,c) #one or more true returns true
d

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [57]:
np.logical_xor(d,c) #same values return false and different values return True

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [58]:
np.where(a <= 0,1/a,a) #where works like conditional statements in C programming checks the condition
#if true then runs second argument, if flase then run third argument

/home/noufal/.local/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([[-0.1       , -0.11111111, -0.125     , -0.14285714, -0.16666667],
       [-0.2       , -0.25      , -0.33333333, -0.5       , -1.        ],
       [        inf,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ]])

In [59]:
# 'inf' shows infinity where division by zero is done

In [60]:
a.nonzero() #its a tuple - consider corresponding elements of the returned array
#notice (2,0) is missing because it is zero

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [61]:
a = np.array([1,2,np.NaN],float)
a
#NaN 'Not a number' is the trick of python to show missing values, very much used in data analytics

array([  1.,   2.,  nan])

In [62]:
np.isnan(a) #check whether there is a NaN present

array([False, False,  True], dtype=bool)

In [63]:
np.isfinite(a) #checks whether the values are finite

array([ True,  True, False], dtype=bool)

In [64]:
a = np.array([1,4,np.NaN,np.Inf],float)
a

array([  1.,   4.,  nan,  inf])

In [65]:
np.isfinite(a)

array([ True,  True, False, False], dtype=bool)

manipulations and complex statistics in next test
# Thank you